spring:
  application:
    name: order-center
  main:
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      load-on-startup: 1
  profiles:
    active: default

camel:
  springboot:
    auto-startup: true
    name: ${spring.application.name}
    message-history: false

order:
  esUrl: http://www.baidu.com
  stanch:
    skipRickControl: false
    skipGetShopGroupInfo: true
  mq:
    trade:
      paidTag: Tag_newc-dev_share_order_paidTag
      refundedTag: Tag_newc-dev_share_order_refundedTag
  orderConfiguration:
    C_TERMINAL:
      discounts:
        -
          orderType: COMMON
          discountComponent:
            - bean:useGoldDiscountComponent
            - bean:useMemberDiscountComponent
            - bean:useCouponComponent
            - bean:useFundDiscountComponent
      itemChecks:
        -
          orderType: COMMON
          itemCheckComponent:
            - bean:riskControlComponent
            - bean:merchantItemCheckComponent
            - bean:stockItemCheckComponent
            - bean:itemPriceCheckComponent
      cartLimit:
        singleItemLimit: 99
        cartItemLimit: 99
        shopItemLimit: 99
      cancelDelay:
        cancelSeconds: 900
        aboutToCancel: 600
      orderAmount:
        -
          orderType: COMMON
          orderAmount: 100
      stockCheck:
        -
          orderType: COMMON
          checkStock: true
          lockStock: false
      autoConfirmDelay:
        -
          orderType: COMMON
          confirmSeconds: 200
