spring:
  application:
    name: order-center
  main:
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      load-on-startup: 1
  profiles:
    active: default

camel:
  springboot:
    auto-startup: true
    name: ${spring.application.name}
    message-history: false

